### ISSUE TITLE
for a moment i thought the NEC/NCR was replaced with FPGA.

### ISSUE THREAD

**Issue by juanpc2018** [A4091/a4091-hardware#1]
53c710
NCR53C720/725

incredible to find NOS.

i was thinking of recreating the mb89352p
https://www.gee-jee.net/?m=201906

there was a very nice SCSI software analyzer somewhere on the Net.

https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-111/DSAP0031844.pdf
https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-X/DSA842000-248.pdf

https://web.archive.org/web/20121122034712/http://wiki.petroskoutoupis.com/index.php5?title=SCSI_Trace
https://sourceforge.net/projects/scsitrace/files/

https://scsiexplorer.com/

**Comment by cdhooper** [comment]
Thank you for this information.
