### ISSUE TITLE
scsi diy active terminator

### ISSUE THREAD

**Issue by juanpc2018** [A4091/a4091-hardware#3]
https://gglabs.us/node/2084

Not as good as Granite Digital but... Open

**Comment by cdhooper** [comment]
While I appreciate learning about new hardware, and encourage your desire to spread information, why are you opening issues against the A4091 hardware to accomplish this? The A4091 hardware design includes both an integrated active terminator and a 50-pin IDC SCSI terminator. The terminator you are linking here from GGLabs does not even use the same SCSI2 connector as the A4091.
